# Generated by Django 5.1.6 on 2025-09-05 20:57

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("trailers", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="trailermeta",
            new_name="trailer_met_cf_vide_c9b2b0_idx",
            old_name="trailer_me_cf_vide_c1b47c_idx",
        ),
        migrations.RenameIndex(
            model_name="trailermeta",
            new_name="trailer_met_video_n_872c88_idx",
            old_name="trailer_me_video_n_d7a8f3_idx",
        ),
        migrations.RenameIndex(
            model_name="trailermeta",
            new_name="trailer_met_upload__51b9d3_idx",
            old_name="trailer_me_upload__e2c1e6_idx",
        ),
        migrations.RenameIndex(
            model_name="trailermeta",
            new_name="trailer_met_is_feat_058292_idx",
            old_name="trailer_me_is_feat_9a3d5b_idx",
        ),
        migrations.RenameIndex(
            model_name="trailermeta",
            new_name="trailer_met_created_171354_idx",
            old_name="trailer_me_created_2f4a8c_idx",
        ),
        migrations.AlterField(
            model_name="trailermeta",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
